[FEAT-42] implement Request Historical Data message
CamonZ/ib_ex pull request #133
Opened 2024-08-17 12:57 UTC by ooddaa

closes #42

Hey @CamonZ  👋

I've put together `RequestHistoricalData` module, please have a look. 

There are some discrepancies btw TWS API docs and the Python client implementation, I tried to lean towards the Python version. 

⚠️ Have not yet tested with live connection as I need to have lunch first 😂

### Sources: 

- [TWS API Historical Data](https://www.interactivebrokers.com/campus/ibkr-api-page/twsapi-doc/#hist-md)
- IB API Python client source code 

### TODOs: 
- test on live connection
- add `get_available_bar_sizes` util function
- add more tests

2024-08-17 21:50 UTC, CamonZ requested changes
@ooddaa Thanks dude! I've some comments, let me know what you think. Tests are failing because you haven't added the implementation of `RequestHistoricalData` in the map in `IbEx.Client.Messages.Requests`

2024-08-17 21:50 UTC, CamonZ commented on lib/ib_ex/client/messages/market_data/request_historical_data.ex
> +  def new(request_id, contract, end_date_time, duration, bar_size, what_to_show, use_rth, format_date, keep_up_to_date) do
IMO, you should pattern match against the contract here, also no `request_id` since that'll get assigned via `Subscribable`

2024-08-17 21:50 UTC, CamonZ commented on lib/ib_ex/client/messages/market_data/request_historical_data.ex
> +        Utils.format_end_date_time(msg.end_date_time),
All these calls to `Utils` should be done in `new`, not here. This gets called when the message is going out which is a terrible place to find out that one of the params the user passed is invalid.

If you want to keep the translation in the last second that's fine but there should be some form of validation on `new` that the passed values are correct.

2024-08-17 21:50 UTC, CamonZ commented on lib/ib_ex/client/messages/market_data/request_historical_data_utils.ex
> +defmodule IbEx.Client.Messages.MarketData.RequestHistoricalData.Utils do
File location is wrong, if you keep the current module name then the file should be in `request_historical_data/utils.ex`.

I'd also check if this logic is not common with requesting realtime bar data updates on which case we should probably move it to something like `/constants/*`

2024-08-17 21:50 UTC, CamonZ commented on lib/ib_ex/client/messages/market_data/request_historical_data_utils.ex
> +  defp duration_unit_to_string(:second), do: "S"
```elixir
@durations %{
  second: "S",
  day: "D",
  week: "W",
  year: "Y"
}

def duration_unit_to_string(value)  do
  case Map.fetch(@durations, value) do
    {:ok, result} -> result
    _ ->  :invalid_args
  end
end
```

Seems like much easier to read than pattern matching all the options into diff function heads

2024-08-17 21:50 UTC, CamonZ commented on lib/ib_ex/client/messages/market_data/request_historical_data_utils.ex
> +  defp duration_unit_to_string(:second), do: "S"
Incidentally, this whole param validation would probably be much simpler with something like Ecto validations with embedded or tableless schemas

2024-08-17 21:50 UTC, CamonZ commented on lib/ib_ex/client/messages/market_data/request_historical_data_utils.ex
> +  def format_end_date_time(_), do: :bad_arguments
I'm using `:invalid_args` everywhere else

2024-08-18 14:31 UTC, ooddaa commented on lib/ib_ex/client/messages/market_data/request_historical_data.ex
> +  def new(request_id, contract, end_date_time, duration, bar_size, what_to_show, use_rth, format_date, keep_up_to_date) do
Could you elaborate on pattern matching against Contract please? 

I will remove `request_id` 👍. 

I was wondering if have you found a way to implement the subscription in such a way so that we can re-use the `request_id` assigned by `Subscribable` when [cancelling the HistoricalData](https://github.com/CamonZ/ib_ex/issues/56) ?

2024-08-18 14:33 UTC, ooddaa commented on lib/ib_ex/client/messages/market_data/request_historical_data.ex
> +  def new(request_id, contract, end_date_time, duration, bar_size, what_to_show, use_rth, format_date, keep_up_to_date) do
Do you mean

```elixir
  def new(%Contract{} = contract, end_date_time, ...) do
```
to prevent passing smth else ?

2024-08-18 17:37 UTC, ooddaa commented on lib/ib_ex/client/messages/market_data/request_historical_data_utils.ex
> +defmodule IbEx.Client.Messages.MarketData.RequestHistoricalData.Utils do
good idea to keep constants in one place

2024-08-18 17:41 UTC, ooddaa commented on lib/ib_ex/client/messages/market_data/request_historical_data_utils.ex
> +  defp duration_unit_to_string(:second), do: "S"
Given my limited experience with Ecto, I don't see it as a `simpler` version of current validations to be honest 🙃 But I'm happy to be persuaded otherwise. 

Where you thinking of replacing `with do` statements in `new` methods with Ecto?

2024-08-18 17:42 UTC, ooddaa commented on lib/ib_ex/client/messages/market_data/request_historical_data.ex
> +        Utils.format_end_date_time(msg.end_date_time),
Refactored this

2024-08-18 20:30 UTC, CamonZ commented on lib/ib_ex/client/messages/market_data/request_historical_data.ex
> +            duration: Durations.format(duration),
On the constants here you can still get `:invalid_args`, what you should do IMO, is 

```elixir
  with {:ok, mssage_id} <- Requests.message_id_for(__MODULE__), 
          {:ok, duration_str} <- Durations.format(duration),
          {:ok, bar_size_str} <- BarSizes.foramt(bar_size), 
          ..... do
          {
            :ok,
            %__MODULE__{
              ...
            }
         }
  else
    {:error, :invalid_args} = e->
          e
    :error ->
      {:error, :not_implemented}
  end
```

That way you ensure that when you build the message you'll get valid inputs or return an error immediately. Otherwise you can end up with an `:invalid_args` as one of the fields and then try serializing that atom which will blow up the client process.

Other than that it looks pretty good, can you squash all the commits in the PR so we have a single commit for it.

Thank you!

2024-08-18 20:32 UTC, CamonZ commented on lib/ib_ex/client/constants/server_versions.ex
> +  @max_client_ver :bond_issuer_id
you should prob update your TWS version or uncommit this file `:pending_price_revision` is 2 versions after `:bond_issuer_id`.

2024-08-19 17:26 UTC, ooddaa commented on lib/ib_ex/client/constants/server_versions.ex
> +  @max_client_ver :bond_issuer_id
I have [IB Gateway 10.19 ](https://www.interactivebrokers.co.uk/en/trading/ibgateway-stable.php), which is the most latest I could find and it only works with `:bond_issuer_id`, I'll uncommit this file.

2024-08-21 11:14 UTC, CamonZ commented on lib/ib_ex/client/messages/market_data/request_historical_data.ex
> +        msg.version,
@ooddaa after the discussion yesterday on slack I looked more in detail into the MR. Since you pointed out the message was throwing an error in TWS I noticed the following issues

First, we don't need to send the version, that's for server versions lower than 124, we're currently in version 187 in the latest master of the official clients, this client is up to date with version 178.

Second, `end_date_time`, when serialized needs to be in the format of `"%Y%m%d-%H:%M:%S"` that'll make the server assume the specified timestamp is in UTC according to the testbed examples and the error message returned when passing wrongly formatted dates 

Third, the valid serialized values for `format_date` are `1` or `2`, a simple bool to int won't work in this case, in fact I believe we should hardcode it to `2` to force the server to send us the bars with a unix timestamp which will be easier to parse. In that same vein we should skip receiving that parameter in `new`

2024-08-21 18:00 UTC, ooddaa commented on lib/ib_ex/client/messages/market_data/request_historical_data.ex
> +        msg.version,
@CamonZ thanks for the pointers! 

In addition to passing extra fields, it turned out I didn't concat the `Contract` fields correctly. Resolved now and it works. 

🙌

2024-08-21 19:14 UTC, ooddaa commented on lib/ib_ex/client/messages/market_data/request_historical_data.ex
> +            duration: Durations.format(duration),
done ✅

2024-08-22 05:48 UTC, CamonZ approved these changes

2024-08-22 05:49 UTC, merged